export const SEND_MESSAGE = 'SEND_MESSAGE';
export const UPDATE_MESSAGE_STATUS = 'UPDATE_MESSAGE_STATUS';
export const ADD_ATTACHED_FILE = 'ADD_ATTACHED_FILE';
export const REMOVE_ATTACHED_FILE = 'REMOVE_ATTACHED_FILE';
export const CLEAN_ATTACHED_FILES = 'CLEAN_ATTACHED_FILES';
export const SET_FILES_ERROR = 'SET_FILES_ERROR';